### PR TITLE
Adding onboarding guides

### PR DESCRIPTION
**Pull request by aymenfurter**
Added a guide to configure Azure API Management (APIM) for new Azure OpenAI resources and consumer applications. Consider this a draft, feel free to modify as needed.

### CODE REVIEW

**Comment by mohamedsaif** [comment]
Great guide. Thanks for the contribution.

**Comment by mohamedsaif** [comment]
This pull request introduces a comprehensive guide for onboarding new Azure OpenAI resources and consumers to Azure API Management (APIM). The guide includes detailed steps for configuring APIM to work with new Azure OpenAI deployments and consumers, along with several prerequisites and sample configurations.

Main changes:

* `guides/onboarding.md`: Added a new guide for onboarding Azure OpenAI resources and consumers. The guide includes:
  * The prerequisites for starting the configuration.
  * A step-by-step guide for onboarding a new Azure OpenAI Resource, which includes ensuring line of sight to OpenAI, granting OpenAI user access to APIM user managed identity, identifying all deployment names associated with OpenAI, creating an APIM backend for OpenAI, updating routing configuration, testing the revision, marking the revision as current, and enforcing deployment-level RBAC.
  * A step-by-step guide for onboarding a new consumer, which includes creating a new product, creating a new subscription for the product, and sharing the APIM OpenAI endpoint, subscription key, and available models with the team.

**Comment by starlightretailceo** [comment]
EPIC THE ACTING ALL HELPFUL AFTER DELETING MY ISSUE WHAT CAUSED YOU TO EVEN THINK OF THROTLING EXCEPTIONS REALLY HOW HYPOCRITIC IT CLEARLY SHOWS ! PERFECT

**Comment by starlightretailceo** [comment]
@microsoftopensource @msftgits because this pull request content never existed here now its added i had my subscription disabled due to risk abusive policy all kudos to the devs behind the repo now acting as if they never saw my deleted repository

**Pull request merged**
